version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: nextauth-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    depends_on:
      - postgres
    env_file:
      - app/.env


  postgres:
    image: postgres:12-alpine
    container_name: nextauth-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nextauth
    
volumes:
  postgres:
    name: nextauth-sample

