version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: nextauth-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true